version: '3'
services:
  api:
    build:
      context: ./api/.
      dockerfile: ../docker/Dockerfile_development
    depends_on:
      - postgres
    env_file:
      - ./env/api.env
    ports:
      - 3001:3001
    volumes:
      - ./api:/usr/src/app:consistent
    command: /usr/src/app/entrypoint.sh
  postgres:
    image: postgres:15
    restart: on-failure
    environment:
      POSTGRES_DB: supanotes
      POSTGRES_USER: supanotes
      POSTGRES_PASSWORD: supanotes
    ports:
      - 9432:5432
    volumes:
      - ./data/pg:/var/lib/postgresql/data:consistent